### ISSUE TITLE
Output as TXT

### ISSUE THREAD

**Issue by f4depo** [firewizard/theia-monitor#1]
Sorry for my ignorance. I've searched but I can't do what I want because of array structure. Summarize, how can I write output as txt? So I can make this process with cron and I can look which files changed with output text files.

**Comment by firewizard** [comment]
Hey - not sure I understand your use case, but if you're asking how you could save the report in a text file (like a log file) than all you have to do is run the monitor without email reporting and redirect the output to a file. something like this: `php theia-monitor.php --path /var/www/ > theia.log` . you can of course expand on this and save each output in a different log file each the monitor runs, using the current datetime - you would probably need a bash script for this.
